--
title: Fleur-Bernadine Bailey
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  recipes:
    title: Recipes
    output: true
    excerpt_separator: "<!--more-->"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    header_feature_image:
    caption:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    header_feature_image:
    caption:
- scope:
    path: ''
    type: recipe
  values:
    layout: recipe
    order:
baseurl: ''
url: https://fleurbailey.github.io
description: STUDENT ART BLOG
avatar: uploads/Icon.jpg
favicon: uploads/Icon.jpg
gridlayout: true
recipemenu: false
header_text: STUDENT ART BLOG
recipecollection: Avocado Based Recipes

# find an image for your own home page and put it into the images folder
header_feature_image: /uploads/artheader.jpg
recipe_bookcover: /uploads/AvoFrontCover.jpg

twitter_username:   #change to your own twitter account
lang: en_gb
footer_text: Copyright 2020 Fleur Bernadine Bailey
rss: false
email_address: hello@fleurbernadine.com
facebook:
flickr:
google_plus:
instagram: whatoxfordeats
linkedin:
pinterest:
soundcloud:
twitter: fleurbernadine
youtube:
share_buttons:
  facebook: true
  twitter: true
  tumblr:
  pinterest:
  linkedin:
  email: true
google_analytics:
disqus_shortname:
str_follow_on: Follow on
str_rss_follow: Follow RSS feed
str_share_on: Share on
str_add_to: Add to
str_email: Email
str_tweet: Tweet
str_pin_it: Pin it
str_next_post: Read More
str_previous_post: Previous post
str_next_page: Next
str_previous_page: Prev
str_javascript_required_disqus: Please enable JavaScript to view comments.
post_navigation: true
paginate: 10
paginate_path: blog/page:num
markdown: kramdown
permalink: pretty
highlighter: rouge
plugins:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
exclude:
- ".jekyll-cache"
- Gemfile
- README.md
